const gifts=[
["−10%","Скидка 10% на разбор","Твоя скидка 10% на формат «Лиза, что делать?». Скопируй код и пришли Лизе в Telegram."],
["Ритуал","Ритуал намерения 10.10","Возьми лист бумаги. Запиши, что больше не хочешь поддерживать, и что выбираешь вместо этого. Определи один шаг на завтра."],
["−15%","Скидка 15% на разбор","Твоя скидка 15% на формат «Лиза, что делать?». Скопируй код и пришли Лизе в Telegram."],
["Деньги","Денежный чек-лист","Назови финансовую цель на месяц. Пересмотри одну ненужную трату. Сделай один конкретный шаг к новому доходу."],
["+1 вопрос","Дополнительный вопрос","Один уточняющий вопрос по той же ситуации без доплаты при новом заказе формата «Лиза, что делать?»."],
["Послание","Послание для тебя","Не обязательно знать весь маршрут. Начни с одного честного решения и маленького действия сегодня."],
["−20%","Скидка 20% на разбор","Твоя скидка 20% на формат «Лиза, что делать?». Скопируй код и пришли Лизе в Telegram."],
["Любовь","Практика про отношения","Где ты соглашаешься против желания? Что боишься озвучить? Как сказать об этом бережно и прямо? Запиши ответы."],
["Руна","Рунический символ Иса","Символическая подсказка: Иса напоминает о паузе. Отдели то, что зависит от тебя, от того, что не зависит. Сделай шаг в первой части."],
["−25%","Скидка 25% на разбор","Твоя скидка 25% на формат «Лиза, что делать?». Скопируй код и пришли Лизе в Telegram."]
];
const canvas=document.querySelector("canvas"),ctx=canvas.getContext("2d"),rotor=document.getElementById("rotor"),spin=document.getElementById("spin"),status=document.getElementById("status"),result=document.getElementById("result"),arc=Math.PI/5;
for(let i=0;i<10;i++){const mid=-Math.PI/2+i*arc;ctx.beginPath();ctx.moveTo(380,380);ctx.arc(380,380,372,mid-arc/2,mid+arc/2);ctx.closePath();ctx.fillStyle=i%2?"#341421":"#7f3048";ctx.fill();ctx.strokeStyle="#e8bd97";ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.translate(380+Math.cos(mid)*248,380+Math.sin(mid)*248);ctx.rotate(mid+Math.PI/2);ctx.textAlign="center";ctx.textBaseline="middle";ctx.font="bold 24px Arial";ctx.fillStyle="#fff0e2";ctx.fillText(gifts[i][0],0,0,145);ctx.restore()}
const storageKey="liza-1010-wheel-v1";let saved=null;try{saved=JSON.parse(localStorage.getItem(storageKey)||"null");if(saved&&(saved.i<0||saved.i>9||!Number.isInteger(saved.i)))saved=null}catch(e){saved=null}
function reveal(){const gift=gifts[saved.i];document.getElementById("gift").textContent=gift[1];document.getElementById("description").textContent=gift[2];document.getElementById("code").textContent="КОД ПОДАРКА: "+saved.code;result.classList.add("show");spin.disabled=true;spin.textContent="ПОДАРОК ПОЛУЧЕН ✦";status.textContent="Результат сохранён в этом браузере."}
if(saved){rotor.style.transition="none";rotor.style.transform="rotate("+(360-saved.i*36)+"deg)";reveal()}
spin.addEventListener("click",()=>{if(saved)return;spin.disabled=true;spin.textContent="КОЛЕСО ВРАЩАЕТСЯ…";status.textContent="Фортуна выбирает твой подарок";const bytes=new Uint32Array(2);if(window.crypto&&crypto.getRandomValues)crypto.getRandomValues(bytes);else{bytes[0]=Math.floor(Math.random()*4294967296);bytes[1]=Math.floor(Math.random()*4294967296)}const i=Math.floor(bytes[0]/4294967296*10);const code="LIZA1010-"+bytes[1].toString(36).toUpperCase();rotor.style.transform="rotate("+(360*7+360-i*36)+"deg)";setTimeout(()=>{saved={i,code};try{localStorage.setItem(storageKey,JSON.stringify(saved))}catch(e){}reveal();result.scrollIntoView({behavior:"smooth",block:"center"})},6150)});
document.getElementById("copy").addEventListener("click",async()=>{if(!saved)return;const msg="Колесо Фортуны Лизы 10.10. "+gifts[saved.i][1]+". Код: "+saved.code;try{await navigator.clipboard.writeText(msg);document.getElementById("copy").textContent="СКОПИРОВАНО ✓"}catch(e){document.getElementById("copy").textContent="СДЕЛАЙ СКРИНШОТ"}});
